Merge tests which verify floating points registers save/restore during context switch
Qthreads/qthreads pull request #130
Opened 2023-05-17 00:32 UTC by cjhackillinois

I added two units tests which utilize FP registers and context switch. This should allow code to use the GP registers or FP registers without an issue. Note, this code tests the use of the floating point registers (lower 64-bits) and not SIMD vector registers (upper 64-bits).

2023-05-19 17:03 UTC, janciesko requested changes

2023-05-19 17:03 UTC, janciesko commented on include/fastcontext/arm-ucontext.h
Unrelated changes

2023-05-19 17:03 UTC, janciesko commented on src/fastcontext/asm.S
Unrelated changes

2023-05-19 17:33 UTC, cjhackillinois commented on src/fastcontext/asm.S
I'll look at remove those changes next week.

2023-07-06 17:50 UTC, janciesko commented
Any updates on this?

2023-07-10 17:56 UTC, cjhackillinois commented on include/fastcontext/arm-ucontext.h
can you point to the unrelated changes?

2023-07-10 17:56 UTC, cjhackillinois commented on src/fastcontext/asm.S
can you point to the unrelated changes?

2023-07-10 17:57 UTC, cjhackillinois commented
I switched laptops and needed to get my environment back up and working. Everything seems to work with `-O3` and fast context.

2023-07-10 18:17 UTC, cjhackillinois commented
@janciesko still learning github here. I look at my repo and it wants me to discard 7 commits before I can sync. 

![image](https://github.com/Qthreads/qthreads/assets/47911162/cf901041-5bbe-41ca-9694-d99302614322)

I assume I would lose my 2 new unit tests, so for now I'm now doing anything. What do you recommend?

2023-07-10 21:32 UTC, janciesko commented
Closing in favor of https://github.com/Qthreads/qthreads/pull/135

2023-07-10 21:32 UTC, closed without merging